
---
- hosts: localhost
  become: no
  connection: local
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/ansible/secrets/aws_config.yaml"
    - "{{ playbook_dir }}/ansible/vars.yaml"

  tasks:

  - name: creating config_v1.yaml
    template:
      src: "{{ playbook_dir }}/conf/config_v1.j2"
      dest: "{{ playbook_dir }}/conf/config_v1.yaml"

  - name: creating config_v2.yaml
    template:
      src: "{{ playbook_dir }}/conf/config_v2.j2"
      dest: "{{ playbook_dir }}/conf/config_v2.yaml"

  - name: creating setup-instance.sh
    template:
      src: "{{ playbook_dir }}/packer/setup-instance.j2"
      dest: "{{ playbook_dir }}/packer/setup-instance.sh"

  - name: creating cleanup.sh
    template:
      src: "{{ playbook_dir }}/script/cleanup.j2"
      dest: "{{ playbook_dir }}/script/cleanup.sh"      


  - name: Launch setup.sh script
    script: "{{ playbook_dir }}/script/setup.sh"
    register: out
    environment:
      AWS_ACCESS_KEY_ID: "{{ ws.aws_access_key }}"
      AWS_ACCESS_KEY: "{{ ws.aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ ws.aws_secret_key }}"
      AWS_SECRET_KEY: "{{ ws.aws_secret_key }}"
      AWS_REGION: "{{ ws.ec2.region }}"
      NGX: "{{ ws.ec2.machines.ngx.type }}"
      LAB_PATH: "{{ playbook_dir }}"
      TF_VAR_key_name: "{{ ws.ec2.key_name }}"
      TF_VAR_machine_type: "{{ ws.ec2.machines.ngx.type }}"
      AWS_DEFAULT_REGION: "{{ ws.ec2.region }}"

  - debug: var=out.stdout_lines
