
---
- hosts: localhost
  become: no
  connection: local
  gather_facts: yes
  vars_files:
    - "{{ playbook_dir }}/ansible/secrets/aws_config.yaml"
    - "{{ playbook_dir }}/ansible/vars.yaml"

  tasks:
    
  - name: Launch cleanup.sh script
    script: "{{ playbook_dir }}/script/cleanup.sh"
    register: out
    environment:
      AWS_ACCESS_KEY_ID: "{{ ws.aws_access_key }}"
      AWS_ACCESS_KEY: "{{ ws.aws_access_key }}"
      AWS_SECRET_ACCESS_KEY: "{{ ws.aws_secret_key }}"
      AWS_SECRET_KEY: "{{ ws.aws_secret_key }}"
      AWS_REGION: "{{ ws.ec2.region }}"
      NGX: "{{ ws.ec2.machines.ngx.type }}"
      LAB_PATH: "{{ playbook_dir }}"
      TF_VAR_key_name: "{{ ws.ec2.key_name }}"
      TF_VAR_machine_type: "{{ ws.ec2.machines.ngx.type }}"
      AWS_DEFAULT_REGION: "{{ ws.ec2.region }}"

  - debug: var=out.stdout_lines
